# Generated by Django 2.0 on 2020-11-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_removed',
            field=models.NullBooleanField(),
        ),
    ]
