# Generated by Django 2.0 on 2020-11-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='signature',
            field=models.TextField(default=''),
        ),
    ]
