# Generated by Django 2.0 on 2020-11-24 15:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_auto_20201124_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='author',
            name='tel',
            field=models.CharField(default=10086, max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='age',
            field=models.IntegerField(db_column='author_age', default=0, null=True),
        ),
    ]
