# Generated by Django 2.0 on 2020-11-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_auto_20201124_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='tel',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
