# Generated by Django 2.0 on 2020-11-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20201124_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='create_time',
        ),
    ]
