# Generated by Django 2.0 on 2020-11-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_author_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='create_time',
        ),
        migrations.AlterField(
            model_name='author',
            name='tel',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
