# Generated by Django 2.0 on 2020-11-24 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_auto_20201124_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='tel',
        ),
    ]
