# Generated by Django 2.0 on 2020-11-24 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20201124_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='author',
            name='tel',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
