# Generated by Django 2.0 on 2020-11-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=100, verbose_name='图书名称')),
                ('author', models.CharField(max_length=100, verbose_name='作者')),
                ('price', models.FloatField(default=0, null=True, verbose_name='价格')),
            ],
        ),
    ]
